// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB01jLBj5CaJZSOSwkSRcuF7RFq_-l-LjA',
    appId: '1:1079364794879:web:cf4dd5bfbb80ab05cd4fca',
    messagingSenderId: '1079364794879',
    projectId: 'melo-chat-app',
    authDomain: 'melo-chat-app.firebaseapp.com',
    storageBucket: 'melo-chat-app.firebasestorage.app',
    measurementId: 'G-5QNBWE8186',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCof2F_YekEaNug1siHvITQmSvNl2hF54k',
    appId: '1:1079364794879:android:6a5c5a53d596d717cd4fca',
    messagingSenderId: '1079364794879',
    projectId: 'melo-chat-app',
    storageBucket: 'melo-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxp4reKO3PmNr-QH2n6O2BfCrP4AFxPz8',
    appId: '1:1079364794879:ios:17d40ddebe41858ecd4fca',
    messagingSenderId: '1079364794879',
    projectId: 'melo-chat-app',
    storageBucket: 'melo-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
